// GENERATED by scripts/simhash.ts - do not edit by hand.
//
// The rules era this build computes (COMPETITIVE.md 2.6a). A run proof is
// executable only by a sim whose RULES_HASH matches the one it was recorded
// under; client and server import this same constant, so they agree by
// construction. Regenerate after ANY change to src/sim/ that moves a number:
// npx tsx scripts/simhash.ts --write
export const RULES_HASH = "5bfe17ff55cb031b17ddeb052e9b385f5e58a1129950848c8aec1bf8a82b6656";

/** Short form for board chips and error copy. */
export const RULES_ERA = RULES_HASH.slice(0, 7);
