// GENERATED by scripts/simhash.ts - do not edit by hand.
//
// The rules era this build computes (COMPETITIVE.md 2.6a). A run proof is
// executable only by a sim whose RULES_HASH matches the one it was recorded
// under; client and server import this same constant, so they agree by
// construction. Regenerate after ANY change to src/sim/ that moves a number:
// npx tsx scripts/simhash.ts --write
export const RULES_HASH = "5489b66a4fb926de88f2539802111c43f8e4bd91aadcfe46816324d9dfa5a0bb";

/** Short form for board chips and error copy. */
export const RULES_ERA = RULES_HASH.slice(0, 7);
