// GENERATED by tools/asset-pipeline/dedupe-textures.mjs — do not edit by hand.
//
// Textures shared by 2+ GLBs, extracted to /assets/tex/ so the same atlas is
// downloaded once instead of once per prop (the dungeon atlas was embedded in
// 57 separate models). Named by 8 hex of their own sha256, so the name changes
// when the bytes do and the server can serve them immutable for a year.
//
// The loader prewarms these BEFORE the model wave — see startModelLoad().
export const SHARED_TEXTURES: readonly string[] = [
  "/assets/tex/t.115a496b.webp", // 7.2 KB, 57 models
  "/assets/tex/t.173ffbeb.webp", // 9.5 KB, 3 models
  "/assets/tex/t.196b435a.webp", // 9.1 KB, 29 models
  "/assets/tex/t.1d69874b.webp", // 42.1 KB, 3 models
  "/assets/tex/t.1e771ddc.webp", // 5.8 KB, 2 models
  "/assets/tex/t.24415b75.webp", // 7.0 KB, 3 models
  "/assets/tex/t.26e99555.webp", // 5.7 KB, 2 models
  "/assets/tex/t.2a6f4b06.webp", // 9.5 KB, 8 models
  "/assets/tex/t.338f8690.webp", // 7.4 KB, 2 models
  "/assets/tex/t.428218bf.webp", // 24.7 KB, 2 models
  "/assets/tex/t.4ce323ee.webp", // 6.7 KB, 2 models
  "/assets/tex/t.56ccdf81.webp", // 9.2 KB, 2 models
  "/assets/tex/t.5f89e4e9.webp", // 8.5 KB, 2 models
  "/assets/tex/t.6ad3ddca.webp", // 7.7 KB, 32 models
  "/assets/tex/t.87c9ff2e.webp", // 6.2 KB, 2 models
  "/assets/tex/t.87d102d4.webp", // 6.9 KB, 4 models
  "/assets/tex/t.95f4e57f.webp", // 7.0 KB, 2 models
  "/assets/tex/t.9e978957.webp", // 6.3 KB, 5 models
  "/assets/tex/t.a77958a8.webp", // 8.5 KB, 5 models
  "/assets/tex/t.a929c22c.webp", // 6.0 KB, 3 models
  "/assets/tex/t.ad192113.webp", // 10.9 KB, 3 models
  "/assets/tex/t.b4c5b55b.webp", // 8.6 KB, 2 models
  "/assets/tex/t.b8eb29b7.webp", // 12.4 KB, 3 models
  "/assets/tex/t.c2b2fc84.webp", // 13.9 KB, 2 models
  "/assets/tex/t.c9199362.webp", // 9.3 KB, 2 models
  "/assets/tex/t.db1b2a8d.webp", // 7.5 KB, 12 models
  "/assets/tex/t.dbed9aac.webp", // 7.0 KB, 17 models
  "/assets/tex/t.ed597c74.webp", // 9.9 KB, 2 models
  "/assets/tex/t.f57333b3.webp", // 12.5 KB, 5 models
];
