/**
 * RULES HASH - the era stamp (COMPETITIVE.md 2.6a).
 *
 * SHA-256 over a BEHAVIORAL PROJECTION of src/sim/, not over its bytes. The era
 * is the scarcest resource in the competitive design: every proof recorded under
 * an evicted era stops being playable, so the hash must move when the NUMBERS
 * move and stay put otherwise.
 *
 * The projection, and why each rule is there:
 *  - Every module is passed through ts.transpileModule with removeComments, so
 *    comments are gone and types are erased. A doc rewrite, a type annotation,
 *    an import-type, or a reformat cannot burn an era. A changed constant still
 *    does, immediately - a balance change IS a rules change.
 *  - roomPurposes.data.json is normalized through JSON.parse then stringify.
 *  - bot.ts is EXCLUDED. It is the test-only scripted policy driver, imported
 *    by the balance tests and tools and by nothing that ships. Tuning the
 *    balance bot must never evict an honest player proof.
 *  - tips.ts contributes its exported KEY SET, not its strings. The keys ARE
 *    state (systemTip pushes a fired key onto Player.tipsSeen, which serialize
 *    includes), so adding or removing a tip is a rules change. Rewriting the
 *    copy is not, and copy is exactly what gets rewritten on a whim.
 *
 * Why the scoping is not fussiness: 20 of the last 40 commits on main touched
 * src/sim/. Under raw-directory hashing an era lasts about two deploys and a
 * typo fix in a comment costs exactly as much as a damage rebalance.
 *
 * Run: npx tsx scripts/simhash.ts            prints the hash
 *      npx tsx scripts/simhash.ts --write    regenerates src/sim/rulesHash.ts
 *
 * test/replay.test.ts recomputes this and fails if the committed constant is
 * stale, so a sim change that forgets to regenerate cannot merge.
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
export const SIM_DIR = join(HERE, "..", "src", "sim");

// Not part of the rules: the test-only bot, and the generated constant itself
// (which would otherwise be a fixed point we could never compute).
const EXCLUDED = new Set(["bot.ts", "rulesHash.ts"]);

/** Behavioral projection of one module: transpiled, comment-free, types erased.
 *  Two files that compute the same thing project to the same text. */
function projectTs(source: string): string {
  return ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.ESNext,
      removeComments: true,
      newLine: ts.NewLineKind.LineFeed,
    },
  }).outputText;
}

/** tips.ts: the KEY SET is state, the strings are copy. */
function projectTips(source: string): string {
  const keys: string[] = [];
  const re = /^ {2}([A-Za-z_][A-Za-z0-9_]*):/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source))) keys.push(m[1]);
  keys.sort();
  return "TIPS_KEYS:" + keys.join(",");
}

/** The projection as an ordered list of name/content pairs. Exported so the
 *  staleness test can assert WHAT the hash covers, not just its value. */
export function simProjection(): [string, string][] {
  const out: [string, string][] = [];
  for (const file of readdirSync(SIM_DIR).sort()) {
    if (EXCLUDED.has(file)) continue;
    const full = join(SIM_DIR, file);
    if (file.endsWith(".json")) {
      out.push([file, JSON.stringify(JSON.parse(readFileSync(full, "utf8")))]);
    } else if (file.endsWith(".ts")) {
      const src = readFileSync(full, "utf8");
      out.push([file, file === "tips.ts" ? projectTips(src) : projectTs(src)]);
    }
  }
  return out;
}

export function computeRulesHash(): string {
  const h = createHash("sha256");
  for (const [name, body] of simProjection()) {
    h.update(name);
    h.update(" ");
    h.update(body);
    h.update(" ");
  }
  return h.digest("hex");
}

const OUT = join(SIM_DIR, "rulesHash.ts");

export function writeRulesHash(hash: string): void {
  const body = [
    "// GENERATED by scripts/simhash.ts - do not edit by hand.",
    "//",
    "// The rules era this build computes (COMPETITIVE.md 2.6a). A run proof is",
    "// executable only by a sim whose RULES_HASH matches the one it was recorded",
    "// under; client and server import this same constant, so they agree by",
    "// construction. Regenerate after ANY change to src/sim/ that moves a number:",
    "// npx tsx scripts/simhash.ts --write",
    "export const RULES_HASH = " + JSON.stringify(hash) + ";",
    "",
    "/** Short form for board chips and error copy. */",
    "export const RULES_ERA = RULES_HASH.slice(0, 7);",
    "",
  ].join("\n");
  writeFileSync(OUT, body);
}

if (process.argv[1] && process.argv[1].endsWith("simhash.ts")) {
  const hash = computeRulesHash();
  if (process.argv.includes("--write")) {
    writeRulesHash(hash);
    console.log("wrote src/sim/rulesHash.ts:", hash);
  } else {
    console.log(hash);
  }
}
